import { useState, useEffect } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowLeft, Download, Star, Loader2, Building, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import jsPDF from "jspdf";
import type { User as SupabaseUser } from "@supabase/supabase-js";

interface FavouriteProgram {
  id: string;
  program_id: string;
  program_name: string;
  university_name: string;
  match_percentage: number;
}

const FavoredPrograms = () => {
  const navigate = useNavigate();
  const [user, setUser] = useState<SupabaseUser | null>(null);
  const [profileName, setProfileName] = useState<string>("Student");
  const [loading, setLoading] = useState(true);
  const [favourites, setFavourites] = useState<FavouriteProgram[]>([]);

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      if (!session?.user) navigate("/auth");
      else { setUser(session.user); fetchData(session.user.id); }
    });
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_, session) => {
      if (!session?.user) navigate("/auth");
      else { setUser(session.user); fetchData(session.user.id); }
    });
    return () => subscription.unsubscribe();
  }, [navigate]);

  const fetchData = async (userId: string) => {
    try {
      setLoading(true);
      const [profileRes, favouritesRes] = await Promise.all([
        supabase.from("profiles").select("full_name").eq("user_id", userId).maybeSingle(),
        supabase.from("favourite_programs").select("*").eq("user_id", userId).order("created_at", { ascending: false }),
      ]);
      if (profileRes.data?.full_name) setProfileName(profileRes.data.full_name);
      setFavourites((favouritesRes.data as any[]) || []);
    } catch (error) {
      console.error("Error fetching data:", error);
      toast.error("Failed to load your favoured programs");
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadPDF = () => {
    if (favourites.length === 0) {
      toast.error("No programs available to download.");
      return;
    }

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - margin * 2;
    let y = 20;

    // Header
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("EduGuide Favoured Programs", pageWidth / 2, y, { align: "center" });
    y += 8;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text("Official Personalized Recommendations Report", pageWidth / 2, y, { align: "center" });
    y += 12;

    // Line
    doc.setDrawColor(200);
    doc.line(margin, y, pageWidth - margin, y);
    y += 10;

    // Student info
    doc.setTextColor(80);
    doc.setFontSize(10);
    doc.text(`Student: ${profileName}`, margin, y);
    const dateStr = new Date().toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" });
    doc.text(`Date: ${dateStr}`, pageWidth - margin, y, { align: "right" });
    y += 14;

    // Programs
    favourites.forEach((fav, i) => {
      if (y > 260) {
        doc.addPage();
        y = 20;
      }

      // Card background
      doc.setFillColor(248, 249, 250);
      doc.roundedRect(margin, y - 4, contentWidth, 28, 3, 3, "F");

      // Number
      doc.setFillColor(59, 130, 246);
      doc.circle(margin + 8, y + 8, 5, "F");
      doc.setTextColor(255);
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.text(`${i + 1}`, margin + 8, y + 11, { align: "center" });

      // Program name
      doc.setTextColor(30);
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text(fav.program_name || "Unknown Program", margin + 18, y + 6);

      // University
      doc.setTextColor(100);
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.text(fav.university_name || "Unknown University", margin + 18, y + 14);

      // Match
      doc.setTextColor(59, 130, 246);
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text(`${fav.match_percentage}% Match`, pageWidth - margin - 5, y + 10, { align: "right" });

      y += 34;
    });

    // Footer
    y += 6;
    doc.setDrawColor(200);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;
    doc.setTextColor(150);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text("Generated by EduGuide Zimbabwe • eduguide.co.zw", pageWidth / 2, y, { align: "center" });

    doc.save(`EduGuide_Favoured_Programs_${profileName.replace(/\s+/g, "_")}.pdf`);
    toast.success("PDF downloaded successfully!");
  };

  const handleClearAll = async () => {
    if (!user) return;
    if (!window.confirm("Are you sure you want to remove all starred programs? This cannot be undone.")) return;
    try {
      const { error } = await supabase.from("favourite_programs").delete().eq("user_id", user.id);
      if (error) throw error;
      setFavourites([]);
      toast.success("All starred programs cleared");
    } catch (error) {
      console.error("Error clearing favourites:", error);
      toast.error("Failed to clear programs");
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-secondary/30 pb-12">
      <header className="sticky top-0 z-50 bg-card border-b border-border">
        <div className="container mx-auto px-4">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center gap-3">
              <Button variant="ghost" size="icon" className="h-9 w-9" onClick={() => navigate("/dashboard")}>
                <ArrowLeft className="w-5 h-5" />
              </Button>
              <div>
                <h1 className="text-sm font-bold text-foreground">Favoured Programs</h1>
                <p className="text-[11px] text-muted-foreground">Your starred recommendations</p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              {favourites.length > 0 && (
                <Button onClick={handleClearAll} size="sm" variant="destructive" className="hidden sm:flex gap-2">
                  <Trash2 className="w-4 h-4" /> Clear All
                </Button>
              )}
              <Button onClick={handleDownloadPDF} size="sm" className="hidden sm:flex gap-2">
                <Download className="w-4 h-4" /> Download PDF
              </Button>
              {favourites.length > 0 && (
                <Button onClick={handleClearAll} size="icon" variant="ghost" className="sm:hidden text-destructive">
                  <Trash2 className="w-5 h-5" />
                </Button>
              )}
              <Button onClick={handleDownloadPDF} size="icon" variant="ghost" className="sm:hidden">
                <Download className="w-5 h-5 text-primary" />
              </Button>
            </div>
          </div>
        </div>
      </header>

      <main className="container mx-auto px-4 py-8 max-w-4xl">
        <div className="flex items-center justify-between mb-8">
          <div>
            <h1 className="text-2xl font-bold text-foreground flex items-center gap-2">
              <Star className="w-6 h-6 text-yellow-500 fill-yellow-500" />
              Your Favoured Programs
            </h1>
            <p className="text-muted-foreground mt-1 text-sm">Review your saved programs before making your final university choices.</p>
          </div>
        </div>

        {favourites.length === 0 ? (
          <Card className="border-dashed border-2 bg-transparent shadow-none">
            <CardContent className="py-16 text-center">
              <Star className="w-12 h-12 mx-auto mb-4 text-muted-foreground/30" />
              <h2 className="text-lg font-semibold text-foreground mb-2">No programs starred yet</h2>
              <p className="text-sm text-muted-foreground mb-6 max-w-sm mx-auto">
                Any programs you star from your recommendations list will appear here for easy access and PDF export.
              </p>
              <Button asChild>
                <Link to="/my-subjects">Get Recommendations</Link>
              </Button>
            </CardContent>
          </Card>
        ) : (
          <div className="grid gap-4">
            {favourites.map((fav, i) => (
              <Card key={fav.id} className="overflow-hidden border-border/60 shadow-sm">
                <CardContent className="p-0">
                  <div className="flex flex-col sm:flex-row items-start sm:items-center">
                    <div className="hidden sm:flex self-stretch w-12 bg-muted/40 items-center justify-center border-r border-border/60">
                      <span className="font-bold text-muted-foreground">{i + 1}</span>
                    </div>
                    <div className="flex-1 p-5 w-full">
                      <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
                        <div>
                          <h3 className="text-lg font-bold text-foreground mb-1 leading-tight">{fav.program_name}</h3>
                          <div className="flex items-center gap-2 text-sm text-muted-foreground">
                            <Building className="w-4 h-4" />
                            <span>{fav.university_name}</span>
                          </div>
                        </div>
                        <div className="flex items-center self-start bg-blue-50 text-blue-700 dark:bg-blue-950/30 dark:text-blue-400 px-3 py-1.5 rounded-lg border border-blue-100 dark:border-blue-900/50">
                          <span className="text-xs font-semibold uppercase tracking-wider mr-2 opacity-80">Match</span>
                          <span className="font-bold text-base">{fav.match_percentage}%</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </main>
    </div>
  );
};

export default FavoredPrograms;
